---
ci:
  autoupdate_schedule: monthly
  skip:
    - ansible-lint
    - pip-compile
default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite
repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.23
    hooks:
      # Compile requirements
      - id: pip-compile
        name: pip-compile requirements.in
        args: [requirements.in, -o, requirements.txt]
      - id: pip-compile
        name: pip-compile requirements-dev.in
        args: [requirements-dev.in, -o, requirements-dev.txt]
        files: ^requirements-dev\.(in|txt)$
      - id: pip-compile
        name: pip-compile requirements-test.in
        args: [requirements-test.in, -o, requirements-test.txt]
        files: ^requirements-dev\.(in|txt)$
      - id: pip-compile
        name: pip-compile docs/requirements.in
        args: [docs/requirements.in, -o, docs/requirements.txt]
        files: ^docs\/requirements\.(in|txt)$
      - id: pip-compile
        name: pip-compile docs/requirements-build.in
        args: [docs/requirements-build.in, -o, docs/requirements-build.txt]
        files: ^docs\/requirements-build\.(in|txt)$
      - id: uv-lock
  - repo: https://github.com/ansible-network/collection_prep
    rev: 1.1.2
    hooks:
      - id: update-docs
        pass_filenames: false
        args:
          - -p
          - .
          - --link-collection
  - repo: https://github.com/ansible/ansible-lint
    rev: v25.9.1
    hooks:
      - id: ansible-lint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # Git style
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: forbid-new-submodules
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: detect-private-key
      # Common errors
      - id: check-symlinks
      - id: debug-statements
      - id: end-of-file-fixer
        exclude_types:
          - svg
          - rst
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: CHANGELOG.md
      # Exclude 'check-executables-have-shebangs'
      # Broken on Docker for Mac
      - id: check-executables-have-shebangs
      # Cross platform
      - id: check-case-conflict
      - id: mixed-line-ending
        args: [--fix=lf]
      # Security
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
      - id: detect-private-key
      # Linters and Formatters
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
        args: ['--autofix', '--no-sort-keys']
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.2.0
    hooks:
      - id: add-trailing-comma
  # Markdown/CommonMark Linter
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        exclude: ^(CHANGELOG\.md)$
  # YAML Formatter
  - repo: https://github.com/google/yamlfmt
    rev: v0.17.2
    hooks:
      - id: yamlfmt
        # Exclude generated files
        exclude: |
          (?x)^(
            changelogs\/\.plugin-cache\.yaml|
            changelogs\/changelog\.yaml
          )$
  - repo: https://github.com/PyCQA/isort
    rev: 6.1.0
    hooks:
      - id: isort
        name: Sort import statements using isort
        args: ["--filter-files"]
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.9.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
  # Could be slower, so keep it last
  - repo: local
    hooks:
      - id: deps
        name: Upgrade constraints files and requirements
        files: ^(pyproject\.toml|.config/.*)$
        always_run: true
        language: python
        language_version: "3.11"
        entry: python3 -m uv pip compile -q --universal --all-extras --output-file=.config/constraints.txt pyproject.toml --upgrade
        pass_filenames: false
        stages:
          - manual
        additional_dependencies:
          - uv>=0.8.18
