---
namespace: "sinetris"
name: "tools"
version: 0.1.2
readme: README.md
authors:
  - Duilio Ruggiero <https://github.com/sinetris>
description: Ansible Collection to manage basic infrastructure components
license_file: LICENSE
tags:
  - infrastructure
  - linux
  - networking
  - security
  - tools
dependencies:
  "ansible.utils": "*" # note: "*" selects the latest version available
repository: https://github.com/sinetris/ansible-tools-collection
documentation: https://sinetris.github.io/ansible-tools-collection
homepage: https://github.com/sinetris/ansible-tools-collection
issues: https://github.com/sinetris/ansible-tools-collection/issues
build_ignore:
  - .ansible
  - .gitignore
  - .tmp
  - .tox
  - .venv
  - .vscode
  - "*.tar.gz"
  - ansible_collections
  - changelogs/.plugin-cache.yaml
  - docs/build
  - tests/output
