---
platforms:
  - name: na

provisioner:
  name: ansible
  playbooks:
    create: ../utils/playbooks/noop.yml
    prepare: ../utils/playbooks/noop.yml
    destroy: ../utils/playbooks/noop.yml

scenario:
  create_sequence:
    - create
  test_sequence:
    - prepare
  destroy_sequence:
    - destroy
