---
- name: Testing PKI
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Set _argument_spec
      ansible.builtin.set_fact:
        _argument_spec: "{{ (lookup('ansible.builtin.file', argument_specs_file) | from_yaml)['argument_specs'] }}"
      vars:
        argument_specs_file: "../../../roles/bind9/meta/argument_specs.yml"
    - name: Verify argument_specs
      ansible.builtin.validate_argument_spec:
        argument_spec: "{{ (lookup('ansible.builtin.file', argument_specs_file) | from_yaml)['argument_specs'][play_name]['options'] }}"
        provided_arguments:
          pki_action: prepare
          pki_ca_type: root-ca
          pki_cert_type: self-signed-cert
          pki_project: demo
      vars:
        play_name: main
        argument_specs_file: "../../../roles/pki/meta/argument_specs.yml"
