---
- name: Test the tox ansible integration
  ansible.builtin.set_fact:
    msg: 'sinetris.tools.bind9 needs tests'
- name: Assert that the filter worked
  ansible.builtin.assert:
    that:
      - msg == 'sinetris.tools.bind9 needs tests'
