---
role_name_check: 1
ansible:
  executor:
    args:
      ansible_playbook:
        - --inventory=${MOLECULE_SCENARIO_DIRECTORY}/../inventory/
        - -vv

dependency:
  name: galaxy

driver:
  name: docker

provisioner:
  name: ansible
  options:
    verbose: true
  config_options:
    defaults:
      collections_path: ${ANSIBLE_COLLECTIONS_PATH}
      deprecation_warnings: false
      remote_tmp: /tmp/.ansible/tmp

scenario:
  test_sequence:
    - dependency
    # - cleanup
    # - destroy
    # - prepare
    # - converge
    - verify
    # - idempotence
    # - verify
    # - cleanup
    # - destroy
