---
name: Release sinetris.tools

on:
  release:
    types:
      - published

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  validate-collection-version:
    uses: ./.github/workflows/validate_collection_version.yml
  update-documentation:
    uses: ./.github/workflows/gh-pages.yml
    needs:
      - validate-collection-version
  release-galaxy:
    uses: ansible/ansible-content-actions/.github/workflows/release_galaxy.yaml@main
    with:
      environment: release
      galaxy_publish: true
    secrets:
      ansible_galaxy_api_key: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
    needs:
      - validate-collection-version
